### ISSUE TITLE
ComponentServiceObjects and ServiceObjects

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#154]
I have the feeling I already asked this before, but here I go again:
`org.osgi.framework.ServiceObjects` and `org.osgi.service.component.ComponentServiceObjects `are besides some minor javadoc differences identical. I get why this needs to be a separate interface, but I don't see a compelling reason why `ComponentServiceObjects` can' t simply extend `ServiceObjects`. The only reason I can imagine is that they may evolve separately in the future that we may want the spec interfaces to be "self contained".

Have I already answered myself or is there more to it?

**Comment by timothyjward** [comment]
> The only reason I can imagine is that they may evolve separately in the future that we may want the spec interfaces to be "self contained".
* ServiceObjects is `@ProviderType`, we don't want DS becoming an implementor of `org.osgi.framework`
  * An update to ServiceObjects in the core spec should not break the implementation of Declarative Services (unimplemented method).
  * DS implementations should work across multiple versions of the OSGi core spec, even though the version of `org.osgi.framework` changes each time
* ComponentServiceObjects fails the *is a* check for inheritance - you wouldn't want to pass a CSO instead of a SO
  * ComponentServiceObjects does caching and tracking linked to the component lifecycle, not the target service lifecycle. If my component is deactivated then my ComponentServiceObjects is closed and cannot be used any more, even if the backing service remains available
  * If my component is deactivated then any unretired instances from the ComponentServiceObjects are released, even if the backing service is still valid.

**Comment by bjhargrave** [comment]
Also, we have an osgi-users@eclipse.org mail list to ask questions like this instead of using the defect reporting mechanism. So I am going to close this issue.
