### ISSUE TITLE
[Features] Provide same MetaData-Fields as Bundle 

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#179]
It would be nice if features would use same Metadata-Fields as Bundle and Subsystem.

|Bundle | Subsystem | Feature
| ------------- |:-------------:| -----:|
|Bundle-Category | Subsystem-Category | ?
|Bundle-ContactAddress | Subsystem-ContactAddress | ?
|Bundle-Copyright | Subsystem-Copyright | ?
|Bundle-Description | Subsystem-Description | description
|Bundle-Developers | ? | ?
|Bundle-DocURL | Subsystem-DocURL | ?
|Bundle-Icon | Subsystem-Icon |
|Bundle-License | Subsystem-License | license
|Bundle-Name | Subsystem-Name | title (maybe rename)
|Bundle-SCM | | ?
|Bundle-SymbolicName | Subsystem-SymbolicName | ?(ArtifactId)
|Bundle-Vendor | Subsystem-Vendor | vendor
|Bundle-Version | Subsystem-Version | version

**Comment by bosschaert** [comment]
Hi @stbischof thanks for the suggestions!

In #196 I added the following attributes: categories, copyright, docURL and SCM.
Name was already there (the codebase does not contain an attribute called 'title').
The Feature ID is similar to the Bundle-Symbolic in combination with the Bundle-Version.
I did not add 'Icon' because the way that is used in bundles/subsystems is to reference a resource inside these archives for its icon. That doesn't really work for features IMHO.
I also didn't add the 'contact address' and 'developers' attributes. This information is often best obtained from the SCM location and/or the documentation.

**Comment by stbischof** [comment]
Thank you!I think that are the Fields we need. 

 When looking at the feature model an option would be to extract this into an additional class nameds 'Meta' or something like that. This may could hold an Map for additional not specifies Headers/Labels/Fields

**Comment by bosschaert** [comment]
Hi @stbischof that's an interesting idea. We could also use a JSON Schema and encode the version in the schema URL, similar to how this is done for XML Schemas in the Remote Service Admin spec https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.remoteserviceadmin.html#d0e92612
