### ISSUE TITLE
org.osgi.test.cases.remoteserviceadmin TCK fails intermittently

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#248]
The org.osgi.test.cases.remoteserviceadmin TCK is not reliable and sometimes fails due to a timing error in the ci build. See <https://github.com/osgi/osgi/runs/2822130509?check_suite_focus=true> for an example.

This needs to be addressed to complete Compendium R8 release.

**Comment by bjhargrave** [comment]
New failure after updated impl: https://github.com/osgi/osgi/runs/3640985975?check_suite_focus=true#step:4:692

**Comment by stbischof** [comment]
i talked with  @timothyjward  about that. 

> Yes, it's a timing thing.

**Comment by timothyjward** [comment]
> i talked with @timothyjward about that. He think that it's a timing thing.

In both of the failures that have occurred since the move to 1.16.1-SNAPSHOT of Aries RSA with mDNS the issue has been in the discovery tests. The ordering of the messages in the logs indicates that mDNS service discovery was particularly slow to resolve when these failures occurred.

It may be that there is also a problem in the discovery provider (I wrote it pretty quickly) but sadly we will always be subject to the whims of the networking gods.

**Comment by timothyjward** [comment]
I have looked further at the test history, and I did find a timing bug in the TCK code which is responsible for at least one of the failures since the implementation update. I have created PR #347
