### ISSUE TITLE
Should the TCK jars be published to Maven Central?

### ISSUE THREAD

**Issue by bjhargrave** [osgi/osgi#293]
When we make a final specification, we will publish the results, including the TCKs, to https://github.com/osgi/materials. We will also publish the API jars to Maven Central as we have done in the past at the OSGi Alliance.

The question here is whether it make sense to publish the TCK jars to Maven Central.

Having the TCK jars in Maven Central can make it useful for implementations to include TCK testing in their builds since they can easily reference the TCK jars from Maven Central. But to run the TCK, you generally need more than the TCK jar itself. Our complete TCK build includes necessary supporting jars such as the proper JUnit and assertj jars required as well as bnd file which define the proper execution of the TCK.

So a build wishing to use the TCK jars from Maven Central to test an implementation would need more than just the TCK jars. The build would need to also provide all the other dependencies and configuration for proper TCK execution.

**Comment by juergen-albert** [comment]
> The question here is whether it make sense to publish the TCK jars to Maven Central.

I would be strongly in favor of deploying the TCKs. We would as suggest integrate it in our normal tests.

> So a build wishing to use the TCK jars from Maven Central to test an implementation would need more than just the TCK jars. The build would need to also provide all the other dependencies and configuration for proper TCK execution.

Do we? It would be nice to have a batteries included version, so everybody can run them without any deeper knowledge. I would expect however that any decent software engineer will be able to setup a decent test with some dependencies. We might want to ask the Eclipse Fdn, but I don't think there is a requirement that TCKs cant have external dependencies. 

I would love if we reach the state, where I only need to add the TCK and the supporting bundles to my workspace, throw it to the resolver and bnd runs the tests.

If I see it correctly, we need to do the following steps to achieve this goal:
* Migrate the tests to run with the normal bnd test mechanism, instead of the hand crafted mechanism we use to install bundles
* Define the set of required and allowed bundles (junit, assertj, OSGitest etc.) 
* Document the requirements and how we expect the tests to be run.

**Comment by bjhargrave** [comment]
The TCK already uses the normal bnd test mechanism. The TCK jars include Test-Cases headers which `bnd runtests` command uses. The TCK jars have all the proper imports for the JUnit/assertj APIs they use, but you need more than that. You need to set the -tester, -runfw, -runproperties and also the -runbundles/-runrequires for the impl you want to test. That cannot all be pre-specified in the TCK build. The bnd files we build as part of the osgi.tck project are that documentation but they are NOT in the TCK jars we would put in Maven Central. They are in the osgi.tck project's jars which aggregate the TCK jars and supporting jars and bnd files.
