### ISSUE TITLE
IllegalArgumentExceptions on ServiceObjects.ungetSetvice

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#350]
We recently stumbled a couple of times over an IllegalArgumentException when calling ServiceObjects.ungetService. In our case we are always in an async process and the service we are calling unget for is already unregistered. According to the org.osgi.framework.ServiceObjects Spec the Exception will be thrown under the following circumstances:
```
 @throws IllegalArgumentException If the specified service object is
	 {@code null} or was not provided by a {@code ServiceObjects}
	 object for the associated service.
```
I can guarantee that both conditions are not meet in our case. It is simply that the service is already unregistered.

I raised the issue for felix: https://issues.apache.org/jira/browse/FELIX-6429

@tjwatson @karlpauls and @cziegeler discussed the issue and believe that this conforms to the spec. If this is the case, we should at least update the Documentation, because it is quite explicit at the moment.

This furthermore brought me to the point, that it appears that I have no chance to check if a `ServiceObjects` or `ServiceReference` is still viable. Besides trying to get the Service Reference again. Especially in the case that I only want to be a good boy and clean up after myself.

**Comment by bjhargrave** [comment]
>  I have no chance to check if a `ServiceObjects` or `ServiceReference` is still viable.

You can already check. ServiceReference.getBundle() != null means the service is still registered. But the result of that check could be invalid as soon as the result is known since another thread can unregister the service. If you really want to be safe, you just need to be prepared for the exception.

**Comment by bjhargrave** [comment]
For a PROTOTYPE_SCOPE service, ServiceObjects.ungetService must _not_ throw an IllegalArgumentException if the service is unregistered. The javadoc states:

> If the associated service has been unregistered, this method returns without doing anything.

**Comment by bjhargrave** [comment]
For a non-PROTOTYPE_SCOPE service, BundleContext.ungetService must _not_ throw an IllegalArgumentException if the service is unregistered. (This also includes using ServiceObjects.ungetService on a non-PROTOTYPE_SCOPE service). The javadoc states:

> If the context bundle's use count for the service is zero or the service has been unregistered, false is returned.

**Comment by juergen-albert** [comment]
> You can already check. ServiceReference.getBundle() != null means the service is still registered. 

Thanks for the Hint. I will check it like this. 

>But the result of that check could be invalid as soon as the result is known since another thread can unregister the service. If you really want to be safe, you just need to be prepared for the exception.

This is true, but as we are ungeting a service here, the result will stay valid as I suspect that the framwork will not reuse service reference Objects.

**Comment by bjhargrave** [comment]
So in all cases ungetting a service that is already unregistered must not result in an exception (assuming all other requirements are met.)

**Comment by bjhargrave** [comment]
> the result will stay valid as I suspect that the framwork will not reuse service reference Objects.

If the result says the service is already unregistered, that will never change. But if the result says the service is registered, and that is the interesting case since you want to unget the service, then the result can change immediately after you know the result.

But, in any case, you should free to safely always unget the service even when the service is unregistered. The impls seem to be wrong here per the javadoc.

**Comment by juergen-albert** [comment]
I suspected and hoped as much. I've forwarded this to the felix bug.

**Comment by tjwatson** [comment]
> @tjwatson @karlpauls and @cziegeler discussed the issue and believe that this conforms to the spec. If this is the case, we should at least update the Documentation, because it is quite explicit at the moment.

My understanding from discussing with @karlpauls was that the IllegalArgumentException was also getting thrown if the same service object was getting passed to `ServiceObjects.ungetService` multiple times.  I agree that an IAE should be thrown for subsequent calls after the first call to `ServiceObjects.ungetService` because after that the service object is no longer provided by the `ServiceObjects`.

I do agree that no IAE must be thrown once the service is unregistered.  I'm fairly certain that was the conclusion from @karlpauls also.

**Comment by juergen-albert** [comment]
In our case, we just have ServiceObjects in my hand. It might be a real Prototyped service or not. I can only guarantee that I `ServiceObjects.getService`  and `ServiceObjects.ungetService` just once. If it has been a singleton and somebody else called unget before me, is out of my hands.

**Comment by bjhargrave** [comment]
> I can only guarantee that I `ServiceObjects.getService` and `ServiceObjects.ungetService` just once. If it has been a singleton and somebody else called unget before me, is out of my hands.

If the service is still registered and ServiceObjects.ungetService is called more than once with the same object, then that is a programming error and IAE is appropriate. 

I get the feeling in this discussion that no one has a real handle on what is actually happening. @juergen-albert you need to do the complete problem determination to fully understand what is actually happening.

**Comment by bjhargrave** [comment]
> then perhaps the IAE is being thrown incorrectly when multiple threads try to unget the identical object?

That would be a framework bug. But until we get a definitive understanding of what is really going on in Jürgen's scenario, we are just guessing...

**Comment by bjhargrave** [comment]
Since this is not a spec bug, can we close this?

**Comment by juergen-albert** [comment]
I think so. We moved the discussion back to the Felix JIRA. We can reopen this if necessary.
