### ISSUE TITLE
[proposal][DS] Support coercion of service properties into a type

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#354]
Currently one needs to define a Map to get the service properties:
```
@Reference
public void bindReference(SomeReference someReference, Map<String, Object> props) {

}
```
For activate/Deactivate methods there is an alternative to specify a "configuration annotation" and is very convient, the same should be possible for bind methods as well.

**Comment by stbischof** [comment]
I recommend to use the [Converter](https://osgi.github.io/osgi/cmpn/util.converter.html#d0e167294) and do the conversation by your own.

But be careful:
Since you only know the Service-Interface `SomeReference`, you do not know which properties are used `configure` the service. Other developers could implement and register a service with different properties then you.

**Comment by rotty3000** [comment]
while I agree with @stbischof of using converter yourself, I don't think you should worry too much about properties you don't expect ahead of time (and could therefore encode in a type safe way) since by definition you don't know about them.

**Comment by laeubi** [comment]
But why should I replicate a function of DS that's already there? That doesn't make much sense ... And as the service will be registered with the properties used to activate the component it makes sense to use the same configuration annotation when consuming that object.

**Comment by stbischof** [comment]
Expecting I implement `SomeReference` as `SomeReferenceImple` and use a Component Property Type Annotation `ConfigAnn`.
When I configure/register the service the the properties would be converted and injected as an `ConfigAnn` into the `activate` method.

If I understand it correctly, you also want to have `ConfigAnn` in your Service when the `SomeReference` is being injected. But my bundle does not export any package. How should the `scr` handle this situation?

**Comment by bjhargrave** [comment]
> For activate/Deactivate methods there is an alternative to specify a "configuration annotation" and is very convient, the same should be possible for bind methods as well.

The problem is disambiguation. In activate/deactivate method we don't pass service objects. In bind methods we do. So when SCR inspects the method signature at runtime, it must decide what each parameter means. Map means service properties. Random type means the service object. That is, SCR cannot easily distinguish between the parameter being a service object or a service properties coercion type. It is not sufficient to look at the parameter type to see if it is an annotation type since there is nothing stopping a service from being registered under an annotation type (since annotation types are interface types).

So without some fundamental changes to how SCR operates, we cannot do this.

**Comment by laeubi** [comment]
> Expecting I implement `SomeReference` as `SomeReferenceImple` and use a Component Property Type Annotation `ConfigAnn`.
> When I configure/register the service the the properties would be converted and injected as an `ConfigAnn` into the `activate` method.
> If I understand it correctly, you also want to have `ConfigAnn` in your Service when the `SomeReference` is being injected. But my bundle does not export any package. How should the `scr` handle this situation?

Either the `ConfigAnn` *is* exported or I can define a `SomeReferenceWellKnownPropertiesAnn`, there is no need/requirement that both using the same annotation and even the `SomeReferenceImple` might not be a dclarative service component.

There are certain services that define a set of properties that *must* be registered along with then (or at least `should`) eg. [Entity Manager Factory (Builder Service)](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.jpa.html#i3087143), so consuming them via a `JPAServiceProperties` annotation would be much more convenient.

> but your configuration annotation object contains none of the expected properties, because the injected service has none of them

Yeah but that's not different compared to having a `Map<>` (beside that there I can't define easily any defaults like with the annotation), so as always I as a consumer need to be aware that I either can handle the case or filter out services without required properties, as well as mentioned above the referenced service might not necessarily be a DS component and might not use the annotation approach at all.

>  I am abivalent, because I never really missed it

I always miss that when I need to parse / access properties of an injected service ... on the other hand, if I first need to define converters and alike that really overkill. If there is a default way to convert Map -> any annotation this might be an alternative but would require additional dependencies and/or calls and that's what one actually wants to avoid with DI.

> The problem is disambiguation. In activate/deactivate method we don't pass service objects. In bind methods we do. So when SCR inspects the method signature at runtime, it must decide what each parameter means. Map means service properties. Random type means the service object. That is, SCR cannot easily distinguish between the parameter being a service object or a service properties coercion type.

That's really a good point but I think it is solvable, for sure there are situations where it might not be possible to use that feature (for sure I can register a service that implements `Map` and that won't work then as well I assume), so I would simply define the following (additional) rule:

everywhere where `Map<>` is a valid parameter also a type where `Type.class.isAnnotation()` returns true is accepted, if this creates a situation where more than one parameter type `Type.class.isAnnotation()` returns true it fails (honestly I can't think of much cases where it is useful to register annotation types but you never know of course) and a `Map<>` must be used instead.

**Comment by laeubi** [comment]
Still useful.

**Comment by laeubi** [comment]
> The problem is disambiguation. In activate/deactivate method we don't pass service objects. In bind methods we do. So when SCR inspects the method signature at runtime, it must decide what each parameter means. Map means service properties. Random type means the service object. That is, SCR cannot easily distinguish between the parameter being a service object or a service properties coercion type. It is not sufficient to look at the parameter type to see if it is an annotation type since there is nothing stopping a service from being registered under an annotation type (since annotation types are interface types).

I have though a bit more about this, would it be an option to require such annotation to use the `@ComponentPropertyType`? That way DS could distinguish between "normal" annotations-as-a-service (even though I have no clue why one should ever do that) and ones meant as configuration objects.

**Comment by bjhargrave** [comment]
> I have though a bit more about this, would it be an option to require such annotation to use the `@ComponentPropertyType`?

Except you want service properties coerced into the type, not component properties. So using `@ComponentPropertyType` to annotated the target type would be a misuse of `@ComponentPropertyType`. It would need a new meta-annotation like `@ServicePropertyType`.

And this coercion would need to supported for field injection and constructor injection as well as method injection.

**Comment by laeubi** [comment]
> Except you want service properties coerced into the type, not component properties.

That is true, but if there would be a restriction you can only use "special annotated" annotations I think it would be sufficient so just take this as an example :-)

> t would need a new meta-annotation like `@ServicePropertyType`.

That sounds reasonable.

> And this coercion would need to supported for field injection and constructor injection as well as method injection.

- [x] method is obvious I think and what I have in mind
- [ ] constructor not sure, what will one get there? I would have assumed this are the usual **component** properties there?
- [ ] field seems odd, how would you get the properties of a field injected service?

**Comment by bjhargrave** [comment]
> It would need a new meta-annotation like `@ServicePropertyType`.

A further problem with this would be that SCR needs to know whether the injection point represents service property coercion (or just a service) at runtime. But inspecting the injection point for some annotation means the annotation must be runtime retention which is a thing we have strenuously avoided for the DS annotations to avoid the package dependency. So, we would need to amend the behavior of the `reference/@field-collection-type` xml attribute to be used by SCR in more cases since SCR would need to disambiguate between a [service](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#org.osgi.service.component.annotations.CollectionType.SERVICE) and [service properties](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#org.osgi.service.component.annotations.CollectionType.PROPERTIES).

**Comment by laeubi** [comment]
At least I would be fine with using this feature for methods only (if it makes thing easier) and as simple as instead of matching

void setSomeService(`MyService` service, `Map`)

match

void setSomeService(`MyService` service, `AnnotationInterface`)

so maybe here https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-method.injection 

between 5 and 6 having

5a - the method takes two arguments, the first is one of 1,2,3,4 and the second is of type `Annotation`

**Comment by bjhargrave** [comment]
There is also a challenge for method injection since the bind method represents a single reference but can take multiple arguments representing the "shape" of the reference (service object, service properties). So we cannot use the xml for the reference to describe the different bind methods arguments like we can for field and constructor injection where each injected value is described by a different reference.

And there is also the case where hand written DS xml can make a single reference element refer to a bind method, and field, and a constructor argument! So SCR can only really analyze the erased type of the injection point at runtime to decide what is to be injected.

I am not convinced this spec complexity is worth its weight. I would just use the original suggestion of just using the [Converter](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/util.converter.html) to coerce the Map into the type.

**Comment by laeubi** [comment]
With the possible ambiguities I wonder if a tool might can encode the method signature in the xml? That would (independently of this change) even prevent DS from searching and matching methods but can request a very specific one.
