### ISSUE TITLE
Provide a ServiceRegistration#tryUnregister() method that returns a boolean instead of throwing an exception

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#454]
Currently the most annoying part when working with `ServiceRegistration` is its behavior to throw an `IllegalStateException` when it has already unregistered and I always wondered what code should do with it, for sure my intend is to unregister it, so if it is already unregistered, fine than I'm a bit late at the party but what should I do then?

So I almost always see some code like this where `ServiceRegistration#unregister` is used:

```
try {
   reference.unregister();
} catch(IllegalArgumentException e) {
 //already unregistered...
}
```

Using Exceptions to report state is bad and for this I'd like to propose a new (maybe default implemented) method like this:
```
/**
 * Try to unregister the service and return the result of this to the caller.
 * 
 * @return <code>true</code> if the {@link ServiceRegistration} was unregistered as a result of this call, <code>false</code> otherwise.
 */
default boolean tryUnregister() {
	try {
		unregister();
		return true;
	} catch(IllegalStateException ise) {
		return false;
	}
}
```
so just in case someone can/want/should do anything useful one can simply do:
```
if (!reference.tryUnregister()) {
  logger.warn("OH NO !!!);
}
```

**Comment by bjhargrave** [comment]
Call: We should survey the use of throwing IllegalStateException in the framework API and make recommendations to elide that for the "closing" methods. (removeListener, ungetService, unregister).

**Comment by tjwatson** [comment]
Note that removing `IllegalStateException` from `org.osgi.framework.ServiceObjects.ungetService(S)` simply replaces the exception with an `IllegalArgumentException` because on the stopped context all service objects would already be cleaned up so there is no way for the framework to tell if the passed in object was provided by the `ServiceObjects` or not.  Should the implementation avoid the IllegalArgumentException if the context is no longer valid also?

**Comment by laeubi** [comment]
> Note that removing IllegalStateException from org.osgi.framework.ServiceObjects.ungetService(S) simply replaces the exception with an IllegalArgumentException because on the stopped context all service objects would already be cleaned up so there is no way for the framework to tell if the passed in object was provided by the ServiceObjects or not. Should the implementation avoid the IllegalArgumentException if the context is no longer valid also?

I would say yes. The whole purpose of this is to allow to clean up at any time, if the serivce registration is already cleaned up anyways there is no point in throwing any exception (except e.g. if passing `null` is forbidden or similar) as the actual goal is already archived.

**Comment by tjwatson** [comment]
I agree, one possible implementation is to simply return quick, as soon as it is detected that the context is no longer valid with no exception.  My original implementation let the method continue but then it detected that there was no object found to remove from the internal references.  There should be no need even to do that check since invalid contexts will already have all their used services released.
