### ISSUE TITLE
Explicit timeout handling on Promise API

### ISSUE THREAD

**Issue by glimmerveen** [osgi/osgi#456]
Currently, when a timeout is specified on a promise, the Promise returned by timeout fails with a TimeoutException when the upstream promise did not resolve beforehand. Handling of a timeout relies on the same operations as "regular" failures. 

If in the failure handling you want to distinguish between a timeout or application failure, you'll need to do an `instanceof` check on the _failure_, which hurts code readability a bit. Adding explicit handlers specifically for timeout related failures could improve the readability of application code.

For example, by extending the Promise API with methods like:

* `Promise<T> onTimeout(Runnable callback)`
* `Promise<T> recoverTimeout(Supplier<? extends T> recovery)`
* `Promise<T> recoverTimeoutWith(Supplier<Promise<? extends T>> recovery)`
* `Promise<T> fallbackTimeoutTo(Promise<? extends T> fallback)`

Though I think application code could benefit from this, I do also see some downsides. Primarily on how these proposed methods would coexist with the use of the existing failure handling operations:
* For example, when there is both an `onFailure` and an `onTimeout` specified, when the timeout triggers, both handlers would be called. I guess preventing the onFailure callback in this case would be a backwards incompatible change, and therefor not an option.
* Also the order of operations would matter. Specifying the `recoverWith` before `recoverTimeoutWith`, could render the latter useless when the former would also (inadvertently) handle the TimeoutException case. This is not really new, as the current API also permits multiple `recoverWith` being chained, which also requires care to ensure each function handles the case(s) it is supposed to.

Any thoughts on this? Would such a change be an acceptable extension? Are there perhaps alternative approaches to timeout handling to be considered?

**Comment by bjhargrave** [comment]
I am convinced this is not a good idea. It would require to spec to define two callback queues (for non-timeout callbacks and for timeout callbacks). And then also to call the right call back depending on the exception type of the failure.

The correct answer here is to do the instanceof check you already mention. Timeout is just one of many exception types which can be present in a promise failure. Recovery code may need to take special action for any number of exception types including TimeoutException.

See https://github.com/bndtools/bnd/blob/271c260085fcc2dd54e912247bdd2c44e6bde902/biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java#L165-L201 where a recovery callback has special handling for multiple exception types including TimeoutException case. Having separate callback queue would complicate recovering from a failure since you need to register for when the failure is a TimeoutException and for when the failure is not a TimeoutException and then possibly duplicate code in both callbacks.

So I do not see sufficient value in additional API for one specific exception type. The additional complexity does not add sufficient value. And I am sure such a change would not be backwards compatible with existing code.

**Comment by rotty3000** [comment]
it's pretty nice as it is if you use Java pattern matching switch:
```java
p.recoverWith(it -> switch (it.getFailure()) {
	case TimeoutException te -> timeoutFailure(te);
	case Throwable t -> generalFailure(t);
});
```
I think we should not change API where the Java language is improving on our behalf.

**Comment by glimmerveen** [comment]
> I am convinced this is not a good idea. It would require to spec to define two callback queues (for non-timeout callbacks and for timeout callbacks). And then also to call the right call back depending on the exception type of the failure.

I was not necessarily suggesting a separate callback queue for timeout related callbacks, but more like additional timeout-specific convenience operations based on the current capabilities/structure. Separate callback queues would address some of the downsides I mentioned, but I fully understand that would be a risky change while also trying to retain the current behaviour: that is most likely not worth it.

> 
> The correct answer here is to do the instanceof check you already mention. Timeout is just one of many exception types which can be present in a promise failure. Recovery code may need to take special action for any number of exception types including TimeoutException.
> 
> See https://github.com/bndtools/bnd/blob/271c260085fcc2dd54e912247bdd2c44e6bde902/biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java#L165-L201 where a recovery callback has special handling for multiple exception types including TimeoutException case. Having separate callback queue would complicate recovering from a failure since you need to register for when the failure is a TimeoutException and for when the failure is not a TimeoutException and then possibly duplicate code in both callbacks.

That is a nice intricate recovery example, thanks for pointing me to it! 

> 
> So I do not see sufficient value in additional API for one specific exception type. The additional complexity does not add sufficient value. And I am sure such a change would not be backwards compatible with existing code.

I see the risk of opening the door for more specific handling, though in this case I would argue that the exception in question is part of the same API, and is raised by the implementation itself; having specific "handler APIs" to deal with that, in addition to the existing failure handling, to me would not be a strange addition. 

Assuming timeout related convenience functions could be added, without messing with the underlying structures (like the callback queues) and existing behaviour (where the example you pointed to depends on), could this be an addition that would be considered?

**Comment by glimmerveen** [comment]
Thanks for this proposal, I think it would be a useful addition! I left some comments on  #461 with some suggestions on the API.
