### ISSUE TITLE
[proposal][connect] allow marking a ConnectContent as resolved

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#466]
When creating a connect-framework one has the ability to provide a classloader for a bundle, but OSGi still tries to resolve the Bundles imports, this can lead to the situation that resolving fails because of missing packages.

It would be good to allow  `ConnectContent` to express in some way, that a missing requirement should be fulfilled by the `ConnectContent` itself (e.g. a missing package is ignored and treated as if this bundle has exported it, or a required capability was fulfilled by the bundle itself), of course this requires special care by the `ConnectContent` provide if this feature is used.

The current alternative is to either build an additional surrogate `ConnectContent` or to modify the header of the `ConnectContent`, both could become quite complex once the connect-framework uses some user supplied input.

**Comment by tjwatson** [comment]
This could be problematic.  If we don't resolve dependencies against other bundles (connect or otherwise) then it risks losing class space consistency.  I realize that a connect class loader could throw out class space consistency anyways, but I prefer to keep the requirements model as clean as we can at the framework level.

The ModuleConnector should provide ConnectContent for all that is required by the bundles it is trying to connect.  Outside of that, if a ModuleConnector wants to drop some requirements it can do so by providing `org.osgi.framework.connect.ConnectContent.getHeaders()` headers that transformed all the requirements to be optional.

**Comment by laeubi** [comment]
> This could be problematic. If we don't resolve dependencies against other bundles (connect or otherwise) then it risks losing class space consistency.

I don't think that resolving should be skipped completely, but if a package is required (but not found anywhere) it would be useful to consume it from the `ConnectContent`, I don't thing this is problematic because it can't be resolved anywhere anywhere else?
