### ISSUE TITLE
Clarify service ranking for default ServletContextHelper of HTTP Whiteboard spec

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#511]
Currently it is not clear from the spec at https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.http.whiteboard.html#service.http.whiteboard.servletcontext which ranking the default ServletContextHelper service should have (by default).

This is important e.g. to register a servlet on "/" for another context as this other context must have a lower service ranking, as otherwise no default context servlets would ever be considered afterwards.

**Comment by cziegeler** [comment]
I agree that it makes sense to include this in the specification as all implementation should use the same service ranking for the default context to make applications portable across implementations.

Other servlet contexts registered at the root can have a higher service ranking than the default context and servlets registered with the default context will still be called. Unless there is a servlet registered with the higher ranked context that process *all* requests. This servlet will obviously process every request and prevend lower ranked contexts to be called.

Proposal: As we have an implementation with Apache Felix out there for several years which registers the default context with a service ranking if Integer.MIN_VALUE, lets add this to the specification (in 8.1)

**Comment by kwin** [comment]
As you outlined correctly in the majority of cases other context should rank higher than the default but for edge cases it should be possible to rank lower. With the default being `Integer.MIN_VALUE` a lower ranking is not possible, i.e. one has to rely on

> In the case of a tie, the lowest service ID is searched first.

That is not very predictable as the service ID depends on the starting order.
Why not giving the default context a ranking like -10000, which allows others to have a lower ranking?

**Comment by bjhargrave** [comment]
> Currently it is not clear from the spec at https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.http.whiteboard.html#service.http.whiteboard.servletcontext which ranking the default ServletContextHelper service should have (by default).

In my reading of the spec, it does not state that the implementation-provided default ServletContextHelper is a registered service. It is just referred to as an implementation. So I do not see that the spec needs to state anything about the service ranking of the implementation-provided default ServletContextHelper since it is not specified to be a registered service.

**Comment by kwin** [comment]
Even if it not necessarily a registered service one needs to know how to create contexts which rank higher or lower than the default.

**Comment by bjhargrave** [comment]
If there is no ServletContextHelper service registered with the service property `osgi.http.whiteboard.context.name=default`, then the implementation-provided default ServletContextHelper is used.

If some bundle registered a ServletContextHelper service with the service property `osgi.http.whiteboard.context.name=default`, then it is claiming the role of the default ServletContextHelper and implementation-provided default ServletContextHelper is not used.

So a bundle registering a ServletContextHelper service with the service property `osgi.http.whiteboard.context.name=default` can use whatever service ranking it desires. It is not relevant since it will override the use of the implementation-provided default ServletContextHelper.

**Comment by kwin** [comment]
I don’t think one should be forced to overwrite the default just to get a predictable order…

**Comment by cziegeler** [comment]
When I suggested to mention the service ranking for the default context, I wasn't literally meaning to specify that this service is registered with that ranking but along the lines of the context behaving like if it is registered with such a ranking.
But I'm also leaning towards @bjhargrave opinion. The reason why the Apache Felix implementation choose to register the default context as a service with minimum value for service ranking is that it exactly behaves like a fallback default.
Based on that I think everything is fine as it is and we can close this issue
