### ISSUE TITLE
org.osgi.service.component.annotations version 1.2 jar is missing on central

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#570]
This one starts at 1.3:

https://mvnrepository.com/artifact/org.osgi/org.osgi.service.component.annotations

It seems 1.2 is part of:

https://mvnrepository.com/artifact/org.osgi/osgi.cmpn

I wonder if it still would be possible to release a separate 1.2 artifacts so applications can use the same maven coordinate but switching just by change the version?

**Comment by timothyjward** [comment]
This is unlikely due to legal headaches. The version you are talking about was produced by the OSGi Alliance under an IP process that required voting on the release artifacts. Unless the artifact was produced in the original build then it would need a new vote from an organisation which no longer exists. If it was part of the build then now (11 years later) it may be hard to reproduce the build sufficiently accurately to create a jar to publish.

**Comment by laeubi** [comment]
If its just a legal issue, afaik Equinox also has included the sources (under EPL) in the `org.eclipse.osgi.services`, beside that, is not the Eclipse OSGi WG the successor of OSGi Alliance? I see a lot of tags in the repo that seem to target OSGi-R5, so the code seems there. Also I can think about just using the cmp jar, strip all unnecessary items so one not need a build from source.

**Comment by HannesWell** [comment]
Can't one put the existing artifact on Central using the Nexus UI and add a manually crafted suitable pom for it?

**Comment by bjhargrave** [comment]
There never existed a `org.osgi.service.component.annotations` version 1.2 artifact. The `org.osgi.service.component.annotations` artifact was created in a later release. So there is no artifact to deploy.

**Comment by HannesWell** [comment]
Understand. Then I got confused by the annotation jar that used to be embedded into Eclipse PDE.

**Comment by laeubi** [comment]
>  Then I got confused by the annotation jar that used to be embedded into Eclipse PDE

probably that jar can be deployed to central?
