### ISSUE TITLE
[Converter] Converting to Optional 

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi#584]
I would like to add some functionality to the Converter by allowing to convert to Optionals.
```
// empty Optional for null
Optional<String> n1 = converter.convert(null).to(Optional.class);
assertThat(n1).isNotNull().isEmpty();

// wrapper for Objects
Optional<String> s1 = converter.convert("1").to(Optional.class);
assertEquals("1", s1.get());


// Respect the Type of the Optional;
//String to Double to Optional
Optional<Double> d = converter.convert("12.3")
		.to(new TypeReference<Optional<Double>>() {
		});
assertEquals(Double.valueOf("12.3"), d.get());

```

This really useful when looking at this Example, when converting to the Interface. 

When having an interface like
```
interface Config {

 default Optional<Integer> a(){
   Optional.empty();
 }

 default Optional<Integer> b(){
   Optional.empty();
 }

 Optional<Integer> c();

 Optional<Integer> d();
}
```

and using a Map as source object

```
Map<String, Object> map = new HashMap<>(); // an example map
map.put("a", 1);
// no b set
map.put("c", 3);
// no d set

Config cfg = converter.convert(map).to(Config.class);
int a = cfg.a();  // Optional.of(1)
int b = cfg.b();  // Optional.empty()
int c = cfg.c();  // Optional.of(3)
int d = cfg.d();  // ConversionException **


```
**
Spec: `If no default is specified and a requested value is not present in the map, a ConversionException is thrown. `
https://docs.osgi.org/specification/osgi.cmpn/8.1.0/util.converter.html
707.4.4.4.4.1 Converting to an Interface

**Comment by laeubi** [comment]
I think it would be worth to have a syntax like this:

`Optional<String> n1 = converter.convert(null).optionalTo(String.class);`

instead of a converter approach, this would then allow a user to try the conversion and check if a value is present.

**Comment by laeubi** [comment]
> When having an interface like

I must confess this defining an interface like this is really odd, as a user I would expect that all cases always work without specifying a useless default method.

**Comment by stbischof** [comment]
All would work, if all values are set. But when the source map does not deliver a value for a key, what to ri?


Currenttly spec sais exception. So Default method is best way to handle that case

**Comment by laeubi** [comment]
> All would work, if all values are set. But when the source map does not deliver a value for a key, what to ri?

`Optional.empty()` ... that's the purpose of an optional to return a value that describes a value (what might be empty) instead of using markers (null, -1, "" ...) or throwing exceptions, requiring to have a value for a method that returns an Optional completely defeats the purpose of an `Optional`.

> Currenttly spec sais exception. So Default method is best way to handle that case

The spec should be adjusted to say:

- if no value is specified an the return value of that method is of any of the java optional types return an empty optional
- otherwise a `ConversionException` is thrown

**Comment by timothyjward** [comment]
I think that what you’re looking for is a scalar mapping for `Optional<T>` where:

* `null` becomes an empty optional
* A value is converted to a `T`
* A value that cannot be converted triggers a failure (failure handlers etc)

I don’t think that this would need new API, just a new rule definition?

**Comment by laeubi** [comment]
> A value that cannot be converted triggers a failure (failure handlers etc)

The use-case for `Optional` is that they do not generate a failure:

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html

> `Optional` is primarily intended for use as a method return type where there is a clear need to represent "no result,"

So if something is not there, or cannot be converted, I simply want an empty optional --> "no result", it doesn't matter because otherwise I won't use an optional.

> I don’t think that this would need new API, just a new rule definition?

Beside making it more clear what happens and to account for more feature rich Type Safety I think new APIs as proposed would be beneficial. Otherwise the value might not what you expect here! This would then make the last example much more clear and simpler (assuming one can already convert String->Double):

```
//String to Double to Optional
Optional<Double> d = converter.convert("12.3").toOptional(Double.class);
assertEquals(Double.valueOf("12.3"), d.get());
```

In contrast, the follwoing would compile but fail with classcast exception in the last line:

```
//Invalid String to Double to Optional
Optional<Double> d = converter.convert("12.3").of(Optional.class);
assertEquals(Double.valueOf("12.3"), d.get());
```

> If we did want to simplify usage somewhat then perhaps a helper method on TypeReference?

Helper methods often are an indication of a bad API design.

**Comment by stbischof** [comment]
@timothyjward i do Not want to change the api. Currebtly its just an additional default mapper mapping that also reapects typereference. Please look into the PR

**Comment by stbischof** [comment]
@laeubi I really would not like to change the API. Thing this ist just an Implementation topic of the existing api.

**Comment by laeubi** [comment]
As said such a default mapper makes no real sense and defeats the purpose of an optional and don't add additional value over just registering a custom typeconverter.

**Comment by laeubi** [comment]
By the way I think assuming that a `Optional<..>` defaults to the empty optional would match user expectation and not really violates the spec, as `Optional`s have an intrinsic default (that is the empty optional), e.g. mapping a Optional to a new value of `null` does not results in an Optional with **the value null** but an empty optional.

**Comment by timothyjward** [comment]
>> A value that cannot be converted triggers a failure (failure handlers etc)
> The use-case for Optional is that they do not generate a failure:
>
> https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html
>
>> Optional is primarily intended for use as a method return type where there is a clear need to represent "no result,"
> So if something is not there, or cannot be converted, I simply want an empty optional --> "no result", it doesn't matter because otherwise I won't use an optional.

The use case for `Optional` is to avoid `NullpointerException`, and the statement above conflates several different cases.

1. The value is present with an empty value, i.e. `null`
2. The value is present with a non-empty, convertible value, e.g. `"42"`
3. The value is present with a non-empty, unconvertible value, e.g.  `"forty-two"`
4. The value is not present at all (i.e. no key mapping for a map-like field).

Option 1 should simply map to an empty optional. It is not possible to have an Optional with the value `null`, and if you try to create one you will either get an exception or an empty optional.

Option 2 should behave in the same way that any other conversion would behave, that is the value is converted to the generic type and wrapped in an optional

Option 3 should also behave in the same way that any other conversion would behave, that is the converter should attempt to convert the value to the generic type, and fail with an exception.

Option 4 should also behave in the same way that a conversion would for any other type.

In summary `Optional` is not special when it comes to conversion, beyond the fact that we need a rule to map `null` to `Optional.empty()` and that the wrapper function is `Optional.of()`. Anything else is a serious deviation from the expected behaviour of the converter and will be confusing to people.


> Beside making it more clear what happens and to account for more feature rich Type Safety I think new APIs as proposed would be beneficial. Otherwise the value might not what you expect here!
> ...

The examples given are examples of *bad* converter usage. You should never use a raw type in this way with the converter. The correct example is:

    //String to Double to Optional
    Optional<Double> d = converter.convert("12.3").to(new TypeReference<Optional<Double>>() {});
    assertEquals(Double.valueOf("12.3"), d.get());

This is type safe, and uses the existing API.

>> If we did want to simplify usage somewhat then perhaps a helper method on TypeReference?
> Helper methods often are an indication of a bad API design.

This is a broadly incorrect statement. A well designed API needs to start with the minimum number of high-level methods to cover all of the necessary use cases. Once that set has been established then common cases should be made simple and readable where possible without overcomplicating the API. 

As an example the `Promise` interface could provide all of its functionality with just two methods. `Promise.getValue()` and `Promise.onResolve(Runnable)`. Every use case can be achieved using only these two methods. The usage, however, would be horrible. The Promise API is a far better API because of *helper* methods like `map` and `flatMap`.


> Optional.empty would be a way to avoid this exception.

@stbischof we shouldn't special case for avoiding this exception. If there's a desirable use for it then it should be a configuration of the converter using a method like `lenient()` which would be a marker to say "don't throw exceptions on conversion failure, just use `null`".

**Comment by stbischof** [comment]
Is there a way to handle this exception with the Rule method in the Converterbuilder?

**Comment by laeubi** [comment]
> The use case for Optional is to avoid NullpointerException, and the statement above conflates several different cases.

I can't find any reference for this in the Javadoc or any other official documentation... You probably can use it for that but that's not its primary use-case.

> Option 4 should also behave in the same way that a conversion would for any other type.

I don't agree here, getting an exception if the value is not there is completely odd as the optional can already express "there is no value" (see the javadoc) so getting an exception is both expensive operation and defeats the whole purpose here, because then I could simply have had not used Optional at all.

That's why I wrote it does not makes sense then anymore, because the value is the effectively not optional at all...

> The correct example is:

What is hard to read, hard to use and makes me feel I never should use the Converter API ;-)

>  Once that set has been established then common cases should be made simple and readable where possible without overcomplicating the API.

Interestingly at OSGi any usefull API is "complicated", while others can (including java itself) handle such "complications" ... your "correct example" clearly shows that you force users to use hard to read boilerplate code instead of providing a nice API that's easy to read, understand and use.

> As an example the Promise interface could provide all of its functionality with just two methods. Promise.getValue() and Promise.onResolve(Runnable). Every use case can be achieved using only these two methods. The usage, however, would be horrible. 

Well thats the point I can always archive everything with other ways, but its less likely to be used if it "horrible" to use ... I really don't get why we suggest users to use horrible APIs and boilerplate instead of adapting to user needs and common practice here, using Exceptions to find out if a value exits or not is really bad in many ways.

**Comment by timothyjward** [comment]
> Is there a way to handle this exception with the Rule method in the Converterbuilder?

You’re looking for an error handler. https://docs.osgi.org/specification/osgi.cmpn/7.0.0/util.converter.html#d0e147674

**Comment by timothyjward** [comment]
> I can't find any reference for this in the Javadoc or any other official documentation... You probably can use it for that but that's not its primary use-case.

`Optional` was created as part of the JSR which created `Stream`. It exists to provide a pleasant experience with things like `findFirst` where “null” would be hard to use. It absolutely does not replace the exception that would occur if your Predicate failed with an exception. 

> I don't agree here, getting an exception if the value is not there is completely odd as the optional can already express "there is no value" (see the javadoc) so getting an exception is both expensive operation and defeats the whole purpose here, because then I could simply have had not used Optional at all.
>
> That's why I wrote it does not makes sense then anymore, because the value is the effectively not optional at all...

Two things:

1. Special cases should be avoided where possible. Making Optional behave differently in this scenario is bad. It adds hidden complexity where the user has to “just know” that the behaviour will be different. 
2. Option 4 isn’t an empty value case. It’s much closer to a `NoSuchMethodError`. The converter converts between many types, including those with methods. We expect there to be a key mapping available and if there isn’t then that is a user error which needs to be signalled. 

Again, you’re trying to use Optional to mean lots of different things at once. This is fine for you in your use right now, but others (including future @laeubi) will be cursing the API when they want to do something subtly different and have no way to separate the concerns. 

> Interestingly at OSGi any usefull API is "complicated", while others can (including java itself) handle such "complications" ...  your "correct example" clearly shows that you force users to use hard to read boilerplate code instead of providing a nice API that's easy to read, understand and use.

For what it’s worth the converter `TypeReference` is more or less identical to the way that the same problem was solved by Java in the Jakarta RESTful Services Client API. Other mapping APIs (e.g. Jackson) have similar needs and solutions. I do not feel that deviating from established precedent would have been considered simpler by most users. Also, when offered the chance to add something else your response was:

 > Helper methods often are an indication of a bad API design.

 Finally 

> using Exceptions to find out if a value exits or not is really bad in many ways.

This isn’t what the converter does. Exceptions are used to identify cases where conversion is impossible or cases where the schema of the source object fails to match the desired target. 

I have proposed an option by which the user could opt out of the exceptions in these cases, which I would be happy to discuss constructively. I am also happy to discuss what we can do with `TypeReference` to help common uses be simpler.

**Comment by stbischof** [comment]
Wen calling get on a Map<String,Optional<?>>with a not set key, you also get an exception.

So i can understand this behavior

**Comment by laeubi** [comment]
> This isn’t what the converter does. Exceptions are used to identify cases where conversion is impossible or cases where the schema of the source object fails to match the desired target.

I can only repeat that for me as a user, an empty optional exactly express that, for what other purpose I should want to use it?

So in the case described by @stbischof here, what is the value of getting either an exception or an Optional that always has a value? So lets assume I want an optional value I need to write code like this:
```
Optional<MyValue> optionalValue;
try {
   optionalValue = <whatever converter call>
} catch(ConversionException e) {
  //ignore its optional ... 
  optionalValue = Optional.empty();
}
... do something useful with it ... maybe computing a default dynamically, use ifPresentOrElse, do other usefull things beyond just preventing a NPE ...
```

This is completely counterintuitive ... Maybe I can use an error handler, what is also cumbersume because I actually can't know what is really meant to be fetched in an optional way (or need to pass state to the handler) and I don't assume it an error condition anyways... Also there is no guarantee that there was not a handler register previously that conflicts with my handler, or there will be a later handler that might could have done something more useful and so on.

That's why I think it would really befit the API and usefulness if there is a way to say "please **try** to convert this value to the desired type and return the result as an optional".
Just having the option to convert the value to an optional if its already there on the other hand might be useful on very special circumstances because then I can simply wrap my call into `Optional.ofNullable(<whatever converter call>)`...

**Comment by timothyjward** [comment]
> I can only repeat that for me as a user, an empty optional exactly express that, for what other purpose I should want to use it?

    String timeout = readTimeOutFromFile();
    long timeout = Converters.standardConverter().convert(timeUnit).to(OptionalLong.class)
        .orElse(5000);

> So in the case described by @stbischof here, what is the value of getting either an exception or an Optional that always has a value? 

This is simply not what happens. You get an empty optional if the key is present and the value is `null`.


I think that the problem you are trying to solve is a different one from support for `Optional`, which is just another scalar type. What you are asking for is to turn off the "schema validation" exception. This is the one that throws an exception when there is a missing key, and it exists to help enforce schemas between map-like types.
    
    @interface Test {
        String foo();
        String fizz();
        String fizzbuzz();
    }
    
    Map<String, String> map = Map.of("foo", "bar", "fizz", "buzz");
    Test test = Converters.standardConverter(map).to(Test.class);
    
    test.foo(); // This is fine;
    test.fizz(); // This is fine;
    test.fizzbuzz(); // This fails as the source schema doesn't match

This behaviour will not be removed as it is an important part of some of the use cases that went into Converter 1.0. I have, however, twice suggested an option that could be used to support what you're asking for without a try/catch block, but you seem not to have seen it either time.

Adding a `lenient()` option when creating the converter would permit the automatic addition of a last-minute error handler by the converter implementation which could map a failure to a `null` conversion. This would then be translated to the appropriate `null` value (e.g. an empty optional) and returned to the client. 

If finer grained control of leniency is needed then an extensible enum would allow different classes of error to be avoided, e.g. `MISSING_KEY`, `CONVERSION_FAILURE`, `NO_HANDLER`...

Finally, leniency could be applied to a single conversion call if we added the method to the `Specifying` interface.

This approach has the benefit of applying to `Functioning` as well to `Converting`, and it avoids the use of Optional to avoid exceptions where Optional is not needed. Furthermore separating leniency from `Optional` support makes the specification simpler and more consistent, and therefore easier to understand and use.
