### ISSUE TITLE
[Versioning Annotations] Allow Version to be repeatable

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#629]
The annotation `org.osgi.annotation.versioning.Version` can currently only be used once per package. For edge cases one wants to export the same package in multiple versions. Therefore it would be helpful to declare that annotation as repeatable (https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html).

**Comment by juergen-albert** [comment]
I do understand where you are coming from, but in general we try to avoid encouraging "wonky" solutions. Thus we are quite hesitant to accommodate your request. 

Sometimes this is necessary on repackaged stuff, which had bad versioning from the start (e.g. in `org.apache.felix.http.servlet-api`), but here Annotations can't be used anyway. They are meant to be used when you write your own Code and help to generate good and clean metadata. If you here have to export something in 2 Versions because a consumer is incapable of using correct version ranges in its requirements, something seems wrong and the whole thing should be corrected at the source.

If it really is necessary, you can already do it manually in your Manifest or bnd file. 

Can you describe your usecase a bit more, as I'm not sure if we may have overlocked something in our consideration of this.

**Comment by kwin** [comment]
This is clearly only relevant for edge cases (where the initial exported version was incorrect). I think it is reasonable to say to not support those edge cases with annotations (as you can built workarounds with manual Manifests or bnd files)
