### ISSUE TITLE
API Bundles should include Requirements for their implementation

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#665]
We usually program again the API jars as build dependencies. This however leads to unfortunate resolve results, as e.g. the configurator often pulls in the ConfigAdmin API but not necessary the implementation. 

We should look through the APIs and decide, if and where it might make sense to add them.

**Comment by laeubi** [comment]
In the past adding to generic Requirements has already lead to problems (e.g. contracts that are never fulfilled or extenders with only a single implementation), and instead then people export fake capabilities from their API using bundles. 

I'm therefore a bit reserved in requiring an implementation from an API bundle that not necessarily implies something, for example for `ConfigAdmin` I can implement a listener and register is so it is picked up **if a Config Admin is there**, so the `ConfigAdmin` is **optional** in my deployment. If the API bundle now requires an implementation, the `ConfigAdmin` suddenly becomes **mandatory** in my deployment and I must include (and manage possibly configure) it and such an implementation might pull in additional other bundles I don't want. 

For example I recently has a discussion with @tjwatson [here](https://github.com/eclipse-equinox/equinox/issues/190#issuecomment-1860595258) about ConfigAdmin not being part of the Eclipse at all, so why include one if only some want to implement some interfaces from it for different scenarios. Also for DS ConfigAdmin (implementation) is not mandatory but optional.

I therefore think an API bundle should **never** require an implementation, also one can have multiple implementation of Services so why just require *one* and not *all* that can potentially be found?

**Comment by tjwatson** [comment]
If an implementation is required it will be required by other bundles that use the API, not the actual API bundle itself.  API bundles are meant to only provide the API, not ensure an actual implementation is there to resolve.  This would lead to the `osgi.implementation` capabilities being useless.  The `osgi.implementation` was designed to give a way to require an implementation because importing the API package was not sufficient.  In the past importing a package was the only way to try and ensure an implementation was going to be present, but that was lacking because it forced the implementing bundles to export the API packages.  Besides that, some specification implementation users may not import an API packages (e.g. service mediator).  The `osgi.implementation` capabilities was defined to solve these problem.

**Comment by timothyjward** [comment]
I agree that adding a requirement to the API jar is not the right solution here. It's almost never the right thing to "fix" a problem by making a change in the wrong place. In the case @juergen-albert describes the issue is that the configurator is missing a requirement for the `ConfigurationAdmin` service. We shouldn't break other users in an effort to fix this.
