### ISSUE TITLE
[DS] Clarify conditions for reactivations in case of exceptions in activate(...)

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#776]
Currently https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-activate.method only states:

>  If the activate method throws an exception, SCR must log an error message containing the exception with the Log Service, if present, and the component configuration is not activated.

It is unclear though under which circumstances the component (a delayed component in this case) is restarted. IIUC for components implementing services this is whenever its service is requested again, for components not implementing services (which are immediate) this will only ever happen if the configuration is touched. Would be good to elaborate a bit on the conditions in https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e32447 and https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e29682. 

That would mean that delayed components stay in state "REGISTERED" in case of exceptions in activate while immediate components stay in state "UNSATISFIED".

**Comment by stbischof** [comment]
@kwin could you please create a test in the component tck that shows the behavior?

**Comment by laeubi** [comment]
> For me it is not clear from the spec currently what one can expect. 

I don't think there is much to expect if the component fails to activate. Just from an OSGi perspective, if it has failed once with the given configuration why should it succeed in the second try? 

That it *might* be retried is either a side-effect (e.g. configuration changes -> component has not `@Modified` -> a new component is tried to be created) or implementation specific.

**Comment by kwin** [comment]
> why should it succeed in the second try?

Because the exception may be recoverable

> That it might be retried is either a side-effect or implementation specific

I don't think it should be, I have observed with Felix SCR that for delayed components it is retried whenever the implemented service is newly requested while for immediate ones only when the config changes.
Would be good to formalize this in a way in order to be able to inspect the failure reason via https://docs.osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/runtime/dto/ComponentConfigurationDTO.html#failure.

**Comment by laeubi** [comment]
> Because the exception may be recoverable

Recoverable exceptions should not be done in the activation, if it is recoverable then you should try (and throw) at the call-site of the methods your service offers.

> I don't think it should be,

What exactly? If your component is immediate, it will always activated only *once*, if you have a configuration then depending on the configuration policy and if you have modify methods different things can happen.

**Comment by laeubi** [comment]
> That would mean that delayed components stay in state "REGISTERED" in case of exceptions in activate while immediate components stay in state "UNSATISFIED".

By the way I think both is wrong, such component should be shown as `FAILED` in both cases...

**Comment by kwin** [comment]
The state `FAILED_ACTIVATION` is depicted in neither https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.component.html#i1445265 nor https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.component.html#i1462979

**Comment by laeubi** [comment]
See https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.FAILED_ACTIVATION

**Comment by kwin** [comment]
I nowhere found any transitions explained from the FAILED_ACTIVATION state, still Felix SCR doesn't treat FAILED_ACTIVATION a final state, that calls for some clarification in the spec.

**Comment by laeubi** [comment]
> I nowhere found any transitions explained from the FAILED_ACTIVATION state, still Felix SCR doesn't treat FAILED_ACTIVATION a final state, that calls for some clarification in the spec.

What do you mean with "final" the spec says 

> The component configuration failed to activate.
> This means the component configuration is satisfied but that either:
>     an exception occurred loading the implementation class,
>     the static initializer threw an exception,
>     the constructor threw an exception, or
>     the activate method threw an exception.
> The failure information from the exception is available from [failure](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.failure).

so that's quite clear to me? 

Nowhere in the spec it is stated that DS must "retry" anything (or will) so maybe the confusion is more about "component descriptions" versus "component configuration" and "component instances"?

e.g. as mentioned before, if the configuration changes, the SCR does not *retry* to activate "the component", it creates a new instance (and the other would have been deactivated)... (assuming you don't have modified method).

**Comment by laeubi** [comment]
There is no retry... and that's your wrong assumption here that anything is retired because of the failed activation.

Regardless of failure, if configuration changes your old component instance is discard and a new one is created that then is activated (and possibly registered). It *might* looks like something is retried but thats not the case it would have happened anyways.

Nerveless the spec would not forbid it that Felix SCR has a mean to configure it in a way to retry failed activation every 30 seconds, but that's nothing that is specified (as it is an implementation detail).

**Comment by laeubi** [comment]
I must confess I lost track what cases you are actually look at, whats your expectation and what do you observe.

Service lookup is a completely different topic, a "delayed component" is only activated once and then reused (unless you use prototype scope) if it fails it is obviously not activated and therefore will possibly be created on (and activated) on each lookup but that's again nothing specified but implementation specific, it would also be allowed to never try to activate the component if it failed once.

So again nothing is "reactivated" _because_ it failed, it was simply never active before...

**Comment by laeubi** [comment]
I think [this part of the spec](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-activation) make it quite clear (emphasis by me):

> Component instances **must never be reused**. Each time a component configuration is activated, **SCR must create a new component instance** to use with the activated component configuration. A component instance must complete activation before it can be deactivated. Once the component configuration is deactivated **or fails to activate due to an exception**, SCR must unbind all the component's bound services and **discard all references to the component instance** associated with the activation.

That means if activation *fails* (as observable by the `ComponentConfigurationDTO#state` having the value `FAILED_ACTIVATION` SCR **must** release all references to the instance, so as per specification there is no way to call `activate` for a given component instance more than once and therefore it can't "reactivate" it.

If after that any thing changes (e.g. services, configurations or service usages) then **a new component instance** is created that then again goes through the activation process again and then it might or might not become activated (and used by others).

**Comment by kwin** [comment]
I just tried with Apache Felix SCR (2.2.12) and this tries activate both immediate and delayed components whenever its implemented service is requested. So for each request a new instance is created and its activate is executed (no matter if the same component (name not instance) failed in its activation before.
This is enough to trigger it:

```
ServiceReference<MyService> ref = bundleContext.getServiceReference(MyService.class)
bundleContext.getService(ref)
```

For either 
```
@Component(service = FailedDelayedComponent.class)
public class FailedDelayedComponentImpl implements FailedDelayedComponent {

    private static final Logger LOGGER = LoggerFactory.getLogger(FailedDelayedComponentImpl.class);
    private static final AtomicInteger ACTIVATE_COUNTER = new AtomicInteger(0);

    @Activate()
    public void activate() {
        LOGGER.error("Called activate of FailedDelayedComponentImpl {} {} times", System.identityHashCode(this), ACTIVATE_COUNTER.incrementAndGet());
        throw new IllegalArgumentException("This component always throws an exception in its activate method.");
    }
}
```

or 

```

**Comment by laeubi** [comment]
> I just tried with Apache Felix SCR (2.2.12) and this tries to activate both immediate and delayed components whenever their implemented services are requested. 

And that's exactly what I have written above... so Felix SCR does not "retry" anything, it just has a changed state (== new service request) and as there is currently no activated component instance it creates one and performs the specified activation process.

See [here](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e29634) for "Immediate Component"

> If an immediate **component configuration** is satisfied and specifies a service, SCR must register the component configuration as a service in the service registry and then activate the component configuration
> ...

The same for a Delayed Component  [described here](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e29682)

> If a delayed component configuration is satisfied, SCR must register **the component configuration** as a service in the service registry but the activation of the component configuration is delayed until the registered service is requested. 

So in both cases the "thing" you see / lookup with `bundleContext.getServiceReference(...)` is the (satisfied) **component configuration** and looking up the actual service object (with `bundleContext.getService(ref)`) SCR creates an new **component instance** and performs the activation.

So the only difference is the time where `activate` is called.

> So for each BundleContext.getService() a new instance is created and its activate is executed (no matter if the same component (name not instance) failed in its activation before)

As said this is an implementation detail of the Felix SCR implementation, I can't find that the spec require this anywhere (but I also can't find it is forbidden), the only exception I can find is for an immediate component is this sentence [here](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e29634):

>  If the activate method throws an Exception, then the component configuration **is not activated and will be discarded**. 

that (for me) seem to indicate that once an immediate component failed activation it has to be never used again (even if its service is requested) but that's not completely prohibited as well.

On the other hand for a delayed component [the spec require](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e29504) it to try activation a component instance at service lookup:

> If this service is requested, SCR must activate the component configuration creating an instance of the component implementation class that will be returned as the service object. 

So in the case of immediate component providing a service **and** failing its initial activation, one might interpret the spec that this component effectively becomes a "delayed" one and Felix SCR seem to handle it that way.

## Summary

To summarize, I think everything is already well defined (especially for configuration changes) SCR itself never retires an activation unless something changes or triggers it, the only thing that *might* can leave some room for interpretation is the case where an immediate component that fails but provides a service is allowed to be requested as a service any longer. But as the spec says that *first* it has to be registered and *then* activated it feels like its at least not forbidden. And SCR is in general quite forgiving when it comes to methods throwing exceptions.

## Question

So for me its a bit unclear what exactly is the goal of your requested clarification? Do you have different behavior in different SCR implementations and need to find out what behaves "more correct"? Because from user perspective an exception should never be used/needed for a component to work and that's actually an important part in OSGi-Services that they are only made visible to other when they are setup and ready to use.
